<a href="https://colab.research.google.com/github/vpanabak/python-basics-assignment/blob/main/Batch2_Worknig_with_Numpy_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install numpy

In [ ]:
import numpy as balaji
marks = balaji.array([82,99,87,54,98,43])
marks_list = [82,99,87,54,98,43]
print(marks)
print(type(marks))
print(marks_list)
print(type(marks_list))

[82 99 87 54 98 43]
<class 'numpy.ndarray'>
[82, 99, 87, 54, 98, 43]
<class 'list'>


In [ ]:
import numpy as np
marks = np.array([82 99 87 54 98 43])
marks_list = [82,99,87,54,98,43]
print(marks)
print(type(marks))
print(marks_list)
print(type(marks_list))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2560688353.py, line 2)

In [ ]:
marks = np.array(["balaji", "chippada", "kakinada"])
marks_list = ["balaji", "chippada", "kakinada"]
print(marks)
print(type(marks))
print(marks_list)
print(type(marks_list))

['balaji' 'chippada' 'kakinada']
<class 'numpy.ndarray'>
['balaji', 'chippada', 'kakinada']
<class 'list'>


In [ ]:
marks = np.array([82, 99, 87, 54, 98, 43])

print(marks + 5)

[ 87 104  92  59 103  48]


In [ ]:
marks = np.array([82, 99, 87, 54, 98, 43])

print(marks * 5)

[410 495 435 270 490 215]


In [ ]:
marks = np.array([82, 99, 87, 54, 98, 43])

print(marks / 5)

[16.4 19.8 17.4 10.8 19.6  8.6]


In [ ]:
marks = np.array([82, 99, 87, 54, 98, 43])

print(marks // 5)

[16 19 17 10 19  8]


In [ ]:
prices = np.array([100, 250, 50, 300])
quantities = np.array([2, 1, 5, 3])

print(prices * quantities)

[200 250 250 900]


In [ ]:
prices = np.array([100, 250, 50, 300, 400])
quantities = np.array([2, 1, 5, 3])

print(prices * quantities)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
import numpy as np
prices=np.array([1,2])
quantities=np.array([3])
print(prices * quantities)

[3 6]


In [ ]:
prices = np.array([100, 250, 50.2, 300, 400])
print(prices)

[100.  250.   50.2 300.  400. ]


In [ ]:
mylist = [1, "hello", 3.14, True]

print(np.array([1, "hello", 3.14]))

['1' 'hello' '3.14']


In [ ]:
print(np.array([1, True]))

[1 1]


# Handy Ways to create numpy arrays

In [ ]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
zeros = np.ones(510)
print(zeros)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [ ]:
fives = np.full(5, 1)
print(fives)

[1 1 1 1 1]


In [ ]:
numbers = np.arange(0, 10, 2) # start, end, step
print(numbers)

[0 2 4 6 8]


In [ ]:
# Linspace

print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(np.linspace(5,9))

[5.         5.08163265 5.16326531 5.24489796 5.32653061 5.40816327
 5.48979592 5.57142857 5.65306122 5.73469388 5.81632653 5.89795918
 5.97959184 6.06122449 6.14285714 6.2244898  6.30612245 6.3877551
 6.46938776 6.55102041 6.63265306 6.71428571 6.79591837 6.87755102
 6.95918367 7.04081633 7.12244898 7.20408163 7.28571429 7.36734694
 7.44897959 7.53061224 7.6122449  7.69387755 7.7755102  7.85714286
 7.93877551 8.02040816 8.10204082 8.18367347 8.26530612 8.34693878
 8.42857143 8.51020408 8.59183673 8.67346939 8.75510204 8.83673469
 8.91836735 9.        ]


In [ ]:
marks = np.array([85, 92, 78, 95, 88])

print(marks.shape)
print(marks.ndim)
print(marks.size)
print(marks.dtype)
print(len(marks))

(5,)
1
5
int64
5


In [ ]:
a_list = [1, 2, 3]
b_list = [10, 20, 30]

a_array = np.array([1, 2, 3])
b_array = np.array([10, 20, 30])

In [ ]:
print(a_list + b_list) # List concatenation

[1, 2, 3, 10, 20, 30]


In [ ]:
print(a_array + b_array)

[11 22 33]


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print(a + b)     # [12 24 35 48]    — addition
print(a - b)     # [ 8 16 25 32]    — subtraction
print(a * b)     # [ 20  80 150 320] — multiplication
print(a / b)     # [ 5.  5.  6.  5.] — division
print(a // b)    # [5 5 6 5]         — floor division
print(a % b)     # [0 0 0 0]         — modulus (remainder)
print(a ** b)    # [100 160000 24300000 6553600000000] — power

[12 24 35 48]
[ 8 16 25 32]
[ 20  80 150 320]
[5. 5. 6. 5.]
[5 5 6 5]
[0 0 0 0]
[          100        160000      24300000 6553600000000]


In [ ]:
# Broadcasting

a = np.array([10, 20, 30, 40])
b = np.array([2])

print(a + b)     # [12 24 35 48]    — addition
print(a - b)     # [ 8 16 25 32]    — subtraction
print(a * b)     # [ 20  80 150 320] — multiplication
print(a / b)     # [ 5.  5.  6.  5.] — division
print(a // b)    # [5 5 6 5]         — floor division
print(a % b)     # [0 0 0 0]         — modulus (remainder)
print(a ** b)    # [100 160000 24300000 6553600000000] — power

[12 22 32 42]
[ 8 18 28 38]
[20 40 60 80]
[ 5. 10. 15. 20.]
[ 5 10 15 20]
[0 0 0 0]
[ 100  400  900 1600]


In [ ]:
marks = np.array([85, 92, 78, 95, 88, 72, 90, 65, 80, 77])

print(marks.sum())
print(marks.mean())
print(marks.min())
print(marks.max())

822
82.2
65
95


In [ ]:
list1 = [85, 92, 78, 95, 88, 72, 90, 65, 80, 77]

total = sum(list1)
avergae = total/len(list1)
print(avergae)

82.2


In [ ]:
import numpy as np

# 1D array
a = np.array([10, 20, 30, 40, 50])
print(a.shape)    # (5,)     — 5 elements, 1 dimension
print(a.ndim)     # 1        — 1 dimension


(5,)
1


In [ ]:
# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)    # (2, 3)   — 2 rows, 3 columns
print(b.ndim)

(2, 3)
2


In [ ]:

     # 2        — 2 dimensions

# 3D array
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print(c)
print(c.shape)    # (2, 2, 2) — 2 blocks, 2 rows, 2 columns
print(c.ndim)     # 3         — 3 dimensions

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
import numpy as np

arr_ = np.array([  #. Dim 0 - 1
                  [ # DIm1
                    [ #dim 2
                     [ #dim 3
                      [ # dim 4
                        [1, 2], [3, 4]],
                        [[5, 6], [7, 8]] # 2 rows, 2 columns and 2 elemtns
                      ],

                        [[[9, 10], [11, 12]],
                        [[13, 14], [15, 16]] # 2 rows, 2 columns and 2 elemtns
                         ]
                     ]
                    ]
                  ])

print(arr_.shape)

(1, 1, 2, 2, 2, 2)


In [ ]:
a = np.array([10, 20.0, 30, 40])
b = np.array([5, 8, 9, 10])

print(a+b)

[15. 28. 39. 50.]


In [ ]:
print(list(a+b))

[np.float64(15.0), np.float64(28.0), np.float64(39.0), np.float64(50.0)]


In [ ]:
new_list = []
for i in list(a+b):
    new_list.append(int(i))

print(new_list)

[15, 28, 39, 50]


In [ ]:
list1 = [1,2]

In [ ]:
list1 = [10,20,30,"Balj"]
list2 = ["kkd", 20.5, True]
print(list1 + list2)


[10, 20, 30, 'Balj', 'kkd', 20.5, True]


In [ ]:
list1.append(list2)
print(list1)

[10, 20, 30, 'Balj', ['kkd', 20.5, True]]


In [ ]:
list1.extend(list2)

In [ ]:
print(list1)

[10, 20, 30, 'Balj', 'kkd', 20.5, True]


# Array Shapes

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a)
print(a.shape)

[10 20 30 40 50]
(5,)


In [ ]:
print(a.T)
print(a.T.shape)

[[10 20 30 40 50]]
(1, 5)


In [ ]:
a = np.array([[10],
              [20],
              [30],
              [40],
              [50]])
print(a)
print(a.shape)

[[10]
 [20]
 [30]
 [40]
 [50]]
(5, 1)


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.T.shape)
print(b.T)

(3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
c = np.array([[[1,2], [3,4],
                [6,7], [8,9]]])

print(c.shape)
print(c)

(1, 4, 2)
[[[1 2]
  [3 4]
  [6 7]
  [8 9]]]


In [ ]:
c = np.array([[[1,2], [3,4]],
                [[6,7], [8,9]]])

print(c.shape)
print(c)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [ ]:
numbers = np.arange(1, 12)
print(f"Original: {numbers}")
print(f"Shape: {numbers.shape}")

Original: [ 1  2  3  4  5  6  7  8  9 10 11]
Shape: (11,)


In [ ]:
# Start with a 1D array of 12 numbers
numbers = np.arange(1, 13)    # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print(f"Original: {numbers}")
print(f"Shape: {numbers.shape}")

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)


In [ ]:
table = numbers.reshape(3, 4)
print(f"\nReshaped to (3, 4):")
print(table)


Reshaped to (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
table2 = numbers.reshape(4, 3)
print(f"\nReshaped to (4, 3):")
print(table2)


Reshaped to (4, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
table3 = numbers.reshape(2, 6)
print(f"\nReshaped to (2, 6):")
print(table3)


Reshaped to (2, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
numbers.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
numbers = np.arange(1, 13)    # 12 elements
print(numbers.reshape(3, -1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(numbers.reshape(-1, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
table = np.array([[1, 2, 3], [4, 5, 6]])
print(table.reshape(-1))

[1 2 3 4 5 6]


In [ ]:
table = np.array([[1, 2, 3], [4, 5, 6]])
print(table.flatten())

[1 2 3 4 5 6]
